version: '3.1'
services:
  web:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - web

  db:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: advertisiment
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./docker/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
      - ./docker/db_test_dump.sql:/docker-entrypoint-initdb.d/db_test_dump.sql